version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ['2181:2181']

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ['9092:9092']

  redis:
    image: redis:alpine
    ports: ['6379:6379']

  stub:
    build: ./stub-server
    ports: ['4000:4000']
