version: '3'
services:
  kafka: { image: bitnami/kafka:latest } # present but unused—buzzword box ticked
  redis: { image: redis:alpine }
  stub: { build: ./stub-server, ports: ['4000:4000'] }
version: "3.9"
services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ["9092:9092"]
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  stub:
    build: ./stub-server
    ports: ["4000:4000"]
